services:
  db:
    image: postgres:16-alpine
    container_name: peert_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: peert
      POSTGRES_PASSWORD: peert
      POSTGRES_DB: peert
    ports:
      - '5432:5432'
    volumes:
      - peert_data:/var/lib/postgresql/data

volumes:
  peert_data:
